import type { CollectionConfig } from "payload";

export const Orders: CollectionConfig = {
  slug: "orders",
  admin: {
    useAsTitle: "orderNumber",
    defaultColumns: ["orderNumber", "customer", "status", "total", "createdAt"],
  },
  fields: [
    { name: "orderNumber", type: "text", required: true, unique: true, admin: { readOnly: true } },
    { name: "customer", type: "relationship", relationTo: "customers" },
    { name: "guestEmail", type: "email" },
    {
      name: "items",
      type: "array",
      required: true,
      fields: [
        { name: "product", type: "relationship", relationTo: "products", required: true },
        { name: "variantSku", type: "text" },
        { name: "quantity", type: "number", required: true, min: 1 },
        { name: "unitPrice", type: "number", required: true },
        { name: "totalPrice", type: "number", required: true },
      ],
    },
    { name: "subtotal", type: "number", required: true },
    { name: "shippingCost", type: "number", required: true, defaultValue: 0 },
    { name: "taxAmount", type: "number", required: true, defaultValue: 0 },
    { name: "discountAmount", type: "number", defaultValue: 0 },
    { name: "total", type: "number", required: true },
    { name: "coupon", type: "relationship", relationTo: "coupons" },
    {
      name: "shippingAddress",
      type: "group",
      fields: [
        { name: "firstName", type: "text", required: true },
        { name: "lastName", type: "text", required: true },
        { name: "company", type: "text" },
        { name: "address1", type: "text", required: true },
        { name: "address2", type: "text" },
        { name: "city", type: "text", required: true },
        { name: "postalCode", type: "text", required: true },
        { name: "country", type: "text", required: true },
        { name: "phone", type: "text" },
      ],
    },
    { name: "shippingMethod", type: "text" },
    { name: "packlinkShipmentId", type: "text" },
    { name: "trackingNumber", type: "text" },
    { name: "trackingUrl", type: "text" },
    { name: "stripePaymentIntentId", type: "text" },
    {
      name: "paymentStatus",
      type: "select",
      required: true,
      defaultValue: "pending",
      options: ["pending", "paid", "failed", "refunded"],
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "pending",
      options: ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"],
    },
    {
      name: "fulfillmentStatus",
      type: "select",
      defaultValue: "unfulfilled",
      options: ["unfulfilled", "partial", "fulfilled"],
    },
    {
      name: "fulfillmentDetails",
      type: "array",
      fields: [
        { name: "provider", type: "text", required: true },
        { name: "externalOrderId", type: "text" },
        { name: "status", type: "text" },
        { name: "itemSkus", type: "array", fields: [{ name: "sku", type: "text" }] },
      ],
    },
    { name: "customerNote", type: "textarea" },
    { name: "internalNote", type: "textarea" },
  ],
};
